### ISSUE TITLE
Bug in diary quality check

### ISSUE THREAD

**Issue by ffranzese** [Ergo-Tools/ActiPASS#67]
The diary file quality check is not case-sensitive, but when processing the diary it is case-sensitive.

A diary file with column names "date", "time", "event", "comments" passes the quality check. However, when using the diary file, it does not work with the error "Not a valid diary file. Continue without diary data". 
The same diary file works for data processing when columns are named "Date", "Time", "Event", "Comments"

**Comment by pasan-h** [comment]
> The diary file quality check is not case-sensitive, but when processing the diary it is case-sensitive.
> 
> A diary file with column names "date", "time", "event", "comments" passes the quality check. However, when using the diary file, it does not work with the error "Not a valid diary file. Continue without diary data". The same diary file works for data processing when columns are named "Date", "Time", "Event", "Comments"

Thanks :-). I think it's fixed now in code. Will be included in next release.
